#关系型数据库配置
[mysql]
host = "121.41.102.241"
port = 3306
database = "tiktok"
username = "root"
password = "Tiktok123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "121.41.102.241"
port = 8080

#阿里云对象存储 tiktok-wzh
[oss]
Endpoint = "https://oss-cn-hangzhou.aliyuncs.com"
AccessKeyID  = "LTAI5tBm9MPHibGVcU76z9QB"
AccessKeySecret = "1fAC3US6DBIR5q2Crc0zVeeyFvg1SR"
Bucket = "tiktok-wzh"
VideoUrl = "https://tiktok-wzh.oss-cn-hangzhou.aliyuncs.com/videos/"
ImageUrl = "https://tiktok-wzh.oss-cn-hangzhou.aliyuncs.com/images/"